
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql : true
  config:
    import: secret.yml
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug
